// Generated by gencpp from file custom_msg/sensor_data.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_SENSOR_DATA_H
#define CUSTOM_MSG_MESSAGE_SENSOR_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg
{
template <class ContainerAllocator>
struct sensor_data_
{
  typedef sensor_data_<ContainerAllocator> Type;

  sensor_data_()
    : id(0)
    , name()
    , temperature(0.0)
    , humidity(0.0)  {
    }
  sensor_data_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , temperature(0.0)
    , humidity(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef float _humidity_type;
  _humidity_type humidity;





  typedef boost::shared_ptr< ::custom_msg::sensor_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::sensor_data_<ContainerAllocator> const> ConstPtr;

}; // struct sensor_data_

typedef ::custom_msg::sensor_data_<std::allocator<void> > sensor_data;

typedef boost::shared_ptr< ::custom_msg::sensor_data > sensor_dataPtr;
typedef boost::shared_ptr< ::custom_msg::sensor_data const> sensor_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::sensor_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::sensor_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::sensor_data_<ContainerAllocator1> & lhs, const ::custom_msg::sensor_data_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.temperature == rhs.temperature &&
    lhs.humidity == rhs.humidity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::sensor_data_<ContainerAllocator1> & lhs, const ::custom_msg::sensor_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg::sensor_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::sensor_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::sensor_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::sensor_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::sensor_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::sensor_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4232267298bafc38ea3a96c60eecc6d5";
  }

  static const char* value(const ::custom_msg::sensor_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4232267298bafc38ULL;
  static const uint64_t static_value2 = 0xea3a96c60eecc6d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/sensor_data";
  }

  static const char* value(const ::custom_msg::sensor_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id \n"
"string name \n"
"float32 temperature \n"
"float32 humidity \n"
;
  }

  static const char* value(const ::custom_msg::sensor_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::sensor_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.temperature);
      stream.next(m.humidity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensor_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::sensor_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::sensor_data_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<float>::stream(s, indent + "  ", v.humidity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_SENSOR_DATA_H
